name: Periodic

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build

      - name: Save artifacts
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v1

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
          path: dist

      - name: Deploy to pages
        run: ./.github/workflows/github-pages-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
