#!/usr/bin/env bash

# From:
# https://www.innoq.com/en/blog/github-actions-automation/

set -eu

repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
remote_name="origin"
main_branch="master"
target_branch="gh-pages"
build_dir="dist"

cd "$GITHUB_WORKSPACE"

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@steventang.net"

git checkout "$target_branch"
find -maxdepth 1 ! -name .git ! -name dist ! -name . -exec rm -rf {} \;
mv dist/* .
git add .

git commit -m "Deploy ${GITHUB_REPOSITORY}: ${GITHUB_SHA}"
if [ $? -ne 0 ]; then
    echo "nothing to commit"
    exit 0
fi

git remote set-url "$remote_name" "$repo_uri"
git push --force-with-lease "$remote_name" "$target_branch"
